# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

bob = User.create!(name: "bob", nickname: "bob")
jane = User.create!(name: "jane", nickname: "jane")

home = Home.create!(address: "2010 BRIGHTWATERS BLVD NE ST PETERSBURG, Florida 33704",
                    price: 3_750_000,
                    user: bob,
                    description: "Mediterranean inspired Waterfront Oasis on Snell Isle in St. Petersburg, FL. Superior craftsmanship combined with elegance defines this custom-built home situated on an oversized lot with deep protected sailboat water. Both inside and out, private and secure, this home is brimming with exceptional architectural details throughout and is an entertainers dream home. Features include an electronic gate entrance, “smart” home wiring system, custom spiral floating staircase with wrought iron railings, a gourmet kitchen with luxury gas appliances, a walk-in climate controlled 1500 bottle wine cellar, a fitness studio, a secluded formal dining room, an executive office with fireplace and water views, a main level & upstairs laundry, and spacious master bedroom with opulent walk in closet and enormous balcony that overlooks downtown St. Petersburg. The lushly landscaped backyard is ideal for entertaining and which includes a large covered terrace with built in outdoor kitchen, a beautiful Pebble-Tec saltwater pool & heated spa, a massive boat dock that accommodates a 60’ vessel, plus an additional boat lift, and much more. This home has something for everyone and is located only a short 5 minute boat / car ride from vibrant downtown St Petersburg where you can enjoy fine dining, shopping boutiques, visit museums and art galleries.",
                    cover_image: File.open(Rails.root.join("db/seeds/image.jpg")))

home = Home.create!(address: "TIERRA VERDE, Florida 33715",
                    price: 5_999_999,
                    description: "Come home to Five Star resort living, in one of the bay area’s most exclusive gulf front enclaves. This estate property offers nearly an acre of tropically landscaped grounds situated on the shores of the Gulf of Mexico and located on Tierra Verde’s premier Oceanview Drive. This stately home is a perfect example of Mediterranean Revival luxury. This home was crafted by Alvarez Homes with only the finest materials and finishes; it features Venetian marble floors, stately columns and soaring ceilings. This gracious home offers 5 bedroom suites all with marble bathrooms. The level of finish and attention to detail is unsurpassed. Some of the amenities include, carved built-ins throughout, solid mahogany doors, 4 artisan crafted floor to ceiling fireplaces, an immense chef’s kitchen with dual granite islands and grand wet bars, 3 dishwashers and 2 ice makers, wine cooler and butler’s pantry. There is also a state of the art home theater / media room for your family and guest’s entertainment. The dining room is large enough to host a banquet sized feast. There is a chairman’s office with French doors and carved built-ins. All of the living spaces open onto beautiful covered verandahs overlooking the spectacular resort style pool and spa. Come home and relax by the pool or in the spa with a great glass of wine and enjoy the sunsets over the gulf, you’ve earned this.",
                    user: bob,
                    cover_image: File.open(Rails.root.join("db/seeds/image2.jpg")))

home = Home.create!(address: "1857 BRIGHTWATERS BLVD NE ST PETERSBURG, Florida 33704",
                    price: 2_995_000,
                    user: jane,
                    description: %{Elegant waterfront estate in St. Petersburg with 180 degree views of open water Tampa Bay. Soaring 21' ceilings, vast water views, a grand spiral staircase, a large double sided fireplace and rich cherry wood floors greet you as you walk through the frontdoor and are just a few of the many architectural elements you will find throughout this spectacular home. It's situated on a large lot and built above required flood elevation = low flood rates. Features include a circular driveway, an oversized attached 3 car garage, an elegant "open" dining room, large mud/laundry room, a gourmet eat - in kitchen with gas stainless appliances, granite counters, walk-in pantry, a lower level guest suite, an impressive master suite with jetted tub, dual vanities, his & hers walk-in dressing rooms, a private viewing balcony and en-suite bedrooms with large walk - ins. Outside you will find an in-ground pool, spa, large boat dock and two boat lifts. This home is located in a sought after neighborhood & just a short ride to vibrant downtown St. Petersburg where you can enjoy fine dining, shopping boutiques, or visit museums and art galleries.},
                    cover_image: File.open(Rails.root.join("db/seeds/image3.jpg")))

home = Home.create!(address: "2027 BRIGHTWATERS BLVD NE ST PETERSBURG, Florida 33704",
                    price: 2_995_000,
                    user: jane,
                    description: "Magnificent custom waterfront home with downtown Tampa Bay views! Located in the highly sought after waterfront community of Snell Isle, this home offers the best of both worlds from both land and sea. It is a true boater’s paradise with docking accommodations for up to a 70’ vessel and is also situated on an oversized lot in a quiet cul-de-sac on Brightwaters Boulevard, located only a 5 minute drive to downtown St. Petersburg. This estate features fabulous architectural details throughout and was built to accentuate sparkling water views from nearly every room. This home features a grand foyer with soaring ceilings and an elegant floating spiral staircase, elevated ceilings, formal entertaining and casual living spaces, a chef’s kitchen with granite countertops, gourmet gas appliances and an abundance of cabinetry, a first floor master retreat with enormous walk in closet, plus an additional guest suite/ office and a vastly oversized 2 car garage. Upstairs you will find three additional spacious en-suite bedrooms with plenty of storage. Outside is an entertainers dream with an oversized pool, spacious yard, and a large private dock equipped with electric & water. Conveniently situated, this home is located only a 15 minute boat ride to downtown Tampa, a 5 minute boat ride to downtown St Petersburg, and a 20 minute ride to the Gulf of Mexico where you can enjoy world class fishing and water sports. Live the Florida lifestyle to the fullest! Beautiful 67' Hatteras Motor Yacht is available for purchase !!",
                    cover_image: File.open(Rails.root.join("db/seeds/image4.jpg")))
